version: '3.7'
services:
    web:
        image: registry.local:5000/nginx:latest
        ports:
          - 8080:80
        networks:
          backend:
          frontend:
            aliases:
              - web
        deploy:
          resources:
            limits:
              cpus: '0.25'
              memory: 128M
            reservations:
              cpus: '0.1'
              memory: 32M

    php:
        image: registry.local:5000/php:latest
        networks:
          - backend
        deploy:
          resources:
            limits:
              cpus: '0.25'
              memory: 128M
            reservations:
              cpus: '0.1'
              memory: 32M

networks:
    frontend:
        name: "frontend"
    backend:
        name: "backend"

